### ISSUE TITLE
11.0.12.8 Win版 存在一些问题

### ISSUE THREAD

**Issue by OcrSu** [alibaba/dragonwell11#139]
https://pic.imgdb.cn/item/611ddae94907e2d39c19afde.png

**Comment by OcrSu** [comment]
11.0.11.7 Win版不存在此问题

**Comment by joeyleeeeeee97** [comment]
Hi, could you provide a test to reproduce this?

**Comment by OcrSu** [comment]
emm，我并不懂这方面，但我知道有问题来反馈

我的完整操作步骤如下：
1.准备PCL2启动器（Minecraft启动器） 以及alibaba/dragonwell11 Win11.0.12.8
PCL2下载链接：https://wwa.lanzoui.com/iYXQ9teepzc
下载链接2：https://pan.baidu.com/s/11wXz7zW1WDDQ-feKWEUKxQ (提取码: aw9q)
Dragonwell11.0.12.8下载链接：https://github.com/alibaba/dragonwell11/releases/tag/11.0.12.8-GA

2.启动  PCL2启动器 （具体可见附图）
切换到设置页面
在游戏java那里选择手动导入（导入Dragonwell11.0.12.8）
此时会弹出错误报告，即次Issues报告的内容
![启动客户端](https://user-images.githubusercontent.com/75876201/133573699-f8d250fd-e643-4ec3-9ae8-814f47df55af.png)
![导入Java11](https://user-images.githubusercontent.com/75876201/133573800-08ac4964-be86-4ad1-9fe2-25e05d3d4cae.png)
![选择Java](https://user-images.githubusercontent.com/75876201/133573826-4aa9513e-277f-488a-aa18-c7ad99750719.png)
![错误报告](https://user-images.githubusercontent.com/75876201/133573908-8891b79e-f1f1-45a8-8ae1-bb760401b773.png)

如果还有什么需要的信息，请留言

**Comment by yuleil** [comment]
您好，请问这个minecraft对应版本的源码或者jar包在哪里可以下载到？

**Comment by yuleil** [comment]
您好，请问PCL是否提供源码？

**Comment by OcrSu** [comment]
> 您好，请问PCL是否提供源码？

没有开源，我会尝试联系作者的
在打开调试模式后，再导入java11进行测试，其日志是这样的
![QQ图片20210926122610](https://user-images.githubusercontent.com/75876201/134793673-e34263cb-1ae0-4afc-bf52-f4d9256965c2.png)

**Comment by OcrSu** [comment]
> 您好，请问PCL是否提供源码？

https://github.com/LTCatt/PCL2Help
