### ISSUE TITLE
什么时候放出window版?

### ISSUE THREAD

**Issue by cielswift** [alibaba/dragonwell11#15]
什么时候放出window版?

**Comment by luchsh** [comment]
Thanks for asking!
For now, I think Windows build will not be available at GA release (March, 2020), the only goal from 11.0.5.1-preview to 11.0.5.1-GA is stability. Binary builds for Windows may be provided in later releases after GA.

**Comment by luchsh** [comment]
It has been a while since the last comment, now closing this issue.
please feel free to re-open if you have more questions on this topic.
