### ISSUE TITLE
[Bug] Cleartext storage of ldap credentials

### ISSUE THREAD

**Issue by anthonyshikanga** [alibaba/dragonwell11#16]
Hi this file is storing ldap credentials publicly https://github.com/alibaba/dragonwell11/blob/08bee80218261f41d976c9828fb94fa5fd4e3284/test/jdk/javax/naming/module/src/test/test/ConnectWithAuthzId.java

```
env.put(Context.PROVIDER_URL, ldapUri.toString());
        env.put(Context.SECURITY_AUTHENTICATION, "simple");
        env.put(Context.SECURITY_PRINCIPAL, "cn=admin,dc=ie,dc=oracle,dc=com");
        env.put(Context.SECURITY_CREDENTIALS, "changeit");
env.put(LdapContext.CONTROL_FACTORIES,
```
https://docs.oracle.com/javase/jndi/tutorial/ldap/security/ldap.html

username is 'admin' and password is 'changeit'

sensitive information disclosure

**Comment by luchsh** [comment]
Thanks for reporting!

The source file you mentioned is just test case, will not be included in the final product.
I think it is OK to leave it as is.
