### ISSUE TITLE
[Request] Please add a windows build for dragonwell11

### ISSUE THREAD

**Issue by akshatGupta2** [alibaba/dragonwell11#17]
I  am wishing and excited to test dragonwell 11 on windows. Please can U release a build . :-)

**Comment by luchsh** [comment]
Thanks for asking!
We do have a plan to support Windows platform, just like Dragonwell 8.
But currently, during preview-to-GA phase, we'd better keep the existing feature set unchanged.
Windows build may be available after GA release.

**Comment by akshatGupta2** [comment]
thanks a lot
