### ISSUE TITLE
钉钉群的二维码过期了

### ISSUE THREAD

**Issue by A11enHuang** [alibaba/dragonwell11#184]
建议在WIKI里面完善说明，Dragonwell8里面的很多特性在11里面用不了，比如尝试使用协程时会提示Unrecognized VM option 'UseWisp2'，另外钉钉的二维码好像过期了，加不了

**Comment by joeyleeeeeee97** [comment]
感谢反馈问题，请加钉钉群 35434688。
您提到缺少的特性说明稍后会补充到wiki
