### ISSUE TITLE
registry.cn-hangzhou.aliyuncs.com/dragonwell/dragonwell11:11.0.7.2-GA_alpine_x86_64 这个镜像下载不下来

### ISSUE THREAD

**Issue by bxvs888** [alibaba/dragonwell11#22]
**Description**
在阿里的镜像服务里查询不到该镜像，也下载docker pull 不下来。

**Steps to Reproduce**
1. Save below snippet '...'
2. Compile it with javac '....'
3. Execute with VM options '....'

**Expected behavior**

**JDK version**
The output of `java -version` command

**Execution environment**
 - OS and version:
 - CPU model:
 - Number of CPU cores:
 - Size of physical memory:
 - Inside Linux container?
   - Linux container name (docker, pouch, etc):
   - Linux container version:

**Comment by luchsh** [comment]
Thanks for reporting! Will have a look.

**Comment by luchsh** [comment]
Have you tried following steps?
<img width="729" alt="截屏2020-06-03 09 48 07" src="https://user-images.githubusercontent.com/1205973/83586564-6872b900-a57f-11ea-9cee-0bcbd3b56732.png">

**Comment by bxvs888** [comment]
我看到这个这个镜像了。这里只有8和11的一个preview版本，镜像版本中没有11.0.7.2的镜像。8的版本可以  pull下来没有问题。

![image](https://user-images.githubusercontent.com/298322/83587085-c227b300-a580-11ea-92c3-1598b80affeb.png)

**Comment by bxvs888** [comment]
@luchsh 
找到了。地址给错了。在上海：
registry.cn-shanghai.aliyuncs.com/dragonwell/dragonwell11:11.0.7.2-GA_alpine_x86_64

**Comment by luchsh** [comment]
确实错了，感谢指正！wiki已经更新
