### ISSUE TITLE
Dragonwell11 是否有 G1ElasticHeap 或类似的归还内存的能力

### ISSUE THREAD

**Issue by jptx1234** [alibaba/dragonwell11#245]
Dragonwell8 的[G1ElasticHeap特性](https://github.com/alibaba/dragonwell8/wiki/Alibaba-Dragonwell8-User-Guide#g1elasticheap)可以把内存归还给操作系统，但在[Dragonwell11 的 wiki](https://github.com/alibaba/dragonwell11/wiki)中未找到类似的说明，请问Dragonwell11是否也有类似的能力，谢谢。

**Comment by ziyilin** [comment]
G1ElasticHeap 只在Dragonwell8中提供，11里是没有的。
