### ISSUE TITLE
[Bug] Failed to compile on windows platform

### ISSUE THREAD

**Issue by joeyleeeeeee97** [alibaba/dragonwell11#25]
**Description**

**Steps to Reproduce**
Run build on windows platform( or use pipeline in http://ci.dragonwell-jdk.io//job/build-scripts/job/jobs/job/jdk11u/job/jdk11u-windows-x64-dragonwell/)

**Expected behavior**
Pass Build on windows

**JDK version**
11.0.8.3 GA

**Execution environment**
 - OS and version: Windows
 - CPU model: x64
 - Number of CPU cores: 4C
 - Size of physical memory: 8G
 - Inside Linux container? 
   - Linux container name (docker, pouch, etc):
   - Linux container version:

**Comment by luchsh** [comment]
Has this issue been fixed yet?

**Comment by joeyleeeeeee97** [comment]
> Has this issue been fixed yet?
Yes. We could close this now.
