### ISSUE TITLE
[Bug] dragonwell11 standard版本在特定环境上UnsafeIntrinsicsTest.java用例报OOM

### ISSUE THREAD

**Issue by sendaoYan** [alibaba/dragonwell11#267]
**Description**
dragonwell11 standard版本在特定环境上UnsafeIntrinsicsTest.java用例报OOM。extended版本运行正常

standard版本：

![image](https://user-images.githubusercontent.com/24123821/186615487-935bde41-67e9-4bfd-8f97-926fbfaf7bea.png)

extended版本：

![image](https://user-images.githubusercontent.com/24123821/186615623-3d8fc53c-5465-42c4-bc1f-b15e3295cd8a.png)

[UnsafeIntrinsicsTest.java.txt](https://github.com/alibaba/dragonwell11/files/9422938/UnsafeIntrinsicsTest.java.txt)

**Steps to Reproduce**
```bash
javac --add-exports java.base/jdk.internal.misc=ALL-UNNAMED UnsafeIntrinsicsTest.java && java -Xmx256M -XX:+UnlockExperimentalVMOptions -XX:+UseZGC --add-modules java.base --add-exports java.base/jdk.internal.misc=ALL-UNNAMED --add-opens java.base/jdk.internal.misc=ALL-UNNAMED UnsafeIntrinsicsTest 
```

**Execution environment**

ESC实例IP：47.98.39.147

![image](https://user-images.githubusercontent.com/24123821/186615194-d0e19fef-2bf9-4695-9667-f598981aead3.png)

**Comment by kelthuzadx** [comment]
ZGC heuristically reserves too many spaces(68% of the heap) for object relocation. There are insufficient spaces to accommodate objects. Object allocation rate is slightly faster than reclamation, which finally leads to OOME. The calculation of reserve space is based on num of concurrent GC threads and parallel GC threads(ZHeuristics::max_reserve), we can use fewer parallel GC threads to reserve more spaces for object allocation and avoid further OOME(e.g. -XX:ParallelGCThreads=5)
