### ISSUE TITLE
[Feature request] Any plans to port Wisp2 to dragonwell11?

### ISSUE THREAD

**Issue by bbarin** [alibaba/dragonwell11#40]
Hey guys!

Do you have any plans to port Wisp2 from dragonwell8 to 11?
We are very keen to use it, but this is stopping us from adopting it.

Best regards,

**Comment by luchsh** [comment]
@yuleil @sanhong  may have the answer

**Comment by yuleil** [comment]
Yes, we will release Wisp 2 on Dragonwell 11 as soon as Wisp2 on Dragonwell 8 is adopted to some users outside Alibaba.
