### ISSUE TITLE
非常期待Windows版本啊！！！

### ISSUE THREAD

**Issue by BruceAn1978** [alibaba/dragonwell11#47]
没有Windows版本，就没法在开发环境下使用，因此更不会直接使用Linux版本进行发布了。

所以说Windows版本是敲门砖，只有开发环境可以使用了，那才会在生产环境部署，运行。

之前看也有好几个帖子询问关于Windows版本的问题，近期有发布计划没有？

**Comment by joeyleeeeeee97** [comment]
http://ci.dragonwell-jdk.io/job/build-scripts/job/jobs/job/jdk11u/job/jdk11u-windows-x64-dragonwell/

**Comment by BruceAn1978** [comment]
👍
