### ISSUE TITLE
版本号不对呀

### ISSUE THREAD

**Issue by 786951355** [alibaba/dragonwell11#48]
11打印的版本号仍然是1.8.201的版本呀。

**Comment by joeyleeeeeee97** [comment]
能否详细说明下哪个平台下哪个版本的jdk11 输出有问题?

**Comment by 786951355** [comment]
> 能否详细说明下哪个平台下哪个版本的jdk11 输出有问题?

抱歉，我刚才看错了，看成系统自带的版本了。
