### ISSUE TITLE
【question】

### ISSUE THREAD

**Issue by skCNA** [alibaba/dragonwell11#58]
dragonwall 11 是否支持warmup 功能

我使用11执行-XX:+CompilationWarmUpRecording -XX:CompilationWarmUpLogfile=/root/jwarmup.log -XX:CompilationWarmUpRecordTime=300 -XX:PrintCompilationWarmUpDetail

stdout：
Unrecognized VM option 'CompilationWarmUpRecording'
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.

**Comment by luchsh** [comment]
从wiki上看来目前是没有的：https://github.com/alibaba/dragonwell11/wiki/Alibaba-Dragonwell-11-Release-Notes

你还可以用这条命令查看你的JVM是否支持某个参数`java -XX:+PrintFlagsFinal -version | grep CompilationWarmUpRecording `

**Comment by skCNA** [comment]
tks

**Comment by skCNA** [comment]
tks
